# Generated by Django 3.1.2 on 2020-11-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201101_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('disabled', 'معطل')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
