# Generated by Django 3.1.2 on 2020-11-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201102_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('نشط', 'active'), ('معطل', 'disabled')], default='active', max_length=50),
        ),
    ]
