# Generated by Django 3.1.2 on 2020-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201102_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('disabled', 'معطل')], default='active', max_length=50),
        ),
    ]
